apiVersion: apps/v1
kind: Deployment
metadata:
  name: velodoc-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velodoc-frontend
  template:
    metadata:
      labels:
        app: velodoc-frontend
    spec:
      containers:
        - name: velodoc-frontend
          image: ismail20022/velodoc-frontend:latest
          ports:
            - containerPort: 80
