# .github/workflows/ci.yml
name: CI FastAPI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - run: |
          pip install -r backend/requirements.txt
          uvicorn backend.app:app --host 0.0.0.0 --port 8000 &
          sleep 5
          curl -f http://localhost:8000/
