name: CI for FastAPI backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run backend and test it
      run: |
        uvicorn backend.app:app --host 0.0.0.0 --port 8000 &
        sleep 5  # Laisse le serveur démarrer
        curl -f http://localhost:8000/  # Fait une requête à la racine
